# builder
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

COPY . .

RUN npm run build

# runner
FROM node:20-alpine AS runner

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

# Копируем собранное приложение
COPY --from=builder /app/dist ./dist

# Копируем Prisma schema и генерируем client в runner
COPY --from=builder /app/prisma ./prisma
RUN npx prisma generate  # ✅ Генерируем Prisma client в runner

EXPOSE 3000

CMD sh -c "npx prisma migrate deploy && node dist/src/main.js"